version: '3'
services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: "apollo-tutorial"
    ports:
      # map localhost to inner net
      - 127.0.0.1:3309:3306
    # dns: 
    #   - 8.8.8.8
    environment:
      # create a DB with root@mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      # map container DB to /usr/local/opt/mysql/8.0/ for persistence
      - ./.mysql:/var/lib/mysql
      - ./configuration/mysql.cnf:/etc/mysql/my.cnf
      - ./.mysql-files:/var/lib/mysql-files

    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=${MYSQL_ROOT_PASSWORD} 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
